framework:
    default_locale: en
    enabled_locales: [ 'en', 'fr' ]
    set_locale_from_accept_language: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
