<?php

declare(strict_types=1);

namespace App\Tests\Unit\Domain\BankTransactions;

use App\Domain\BankTransactions\TypeAndCategoryGuesser;
use App\Domain\Data\ValueObject\BankTransactionCategory;
use App\Domain\Data\ValueObject\BankTransactionType;
use App\Tests\Unit\UnitTestCase;
use PHPUnit\Framework\Attributes\TestWith;

final class TypeAndCategoryGuesserTest extends UnitTestCase
{
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 16.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 16.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingMiscellaneousExpenses, 'PRELEVEMENT DE SDC LES NOUVELLES CHES REF : SIG/11112222/2024-12-15 PRELEVEMENT DU 15/12/2024'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 14.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 14.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB LEJEUNE        14.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB FRANPRIX       14.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB KEOLIS LYON 69 12.12.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF VOYAGEURS 12.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesRestaurant, 'ACHAT CB CHIKIN BANG    12.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingElectricity, 'PRELEVEMENT DE EDF clients parti iers REF : Z127611111111 11111 1 S 114'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingOther, 'ACHAT CB AMAZON PAYMENT 10.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::AestheticAndCareHair, 'ACHAT CB L EPICURIE    10.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingOther, 'ACHAT CB AMAZON PRIME F 10.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::Withdrawal, 'CARTE X2458    10/12/24 A 13H16 RETRAIT DAB LA BANQUE POSTALE'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT POUR M ALLIAUME HUGO COMPTE FR99********************* DEFAULT'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 09.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB CGF17238PAUL1  09.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE Hugo Alliaume Envoye depuis Revolut'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SUMUP   SYMFON 06.12.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB 41260107 Dean  08.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesFastFood, 'ACHAT CB McDonalds 1    05.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB Osterr.Postbus 08.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SundayHandelsG 07.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB Hofer Dankt    07.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB E WOK RESTAURA 05.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE Hugo Alliaume Envoye depuis Revolut'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE ECHEANCE PRET REF : 241202112233 2099XXXX99X99999    E0011223O1 IDENT : FR99XXX112233'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::LeisureSport, 'PRELEVEMENT DE SAS Fitness Ville nche REF : apt-12-1122334-aaAABBcc L Appart Fitness Villefranche -'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::VariousInsurance, 'PRELEVEMENT DE LBP ASSURANCES IA REF : 160011122334 XXX00160011122334 NM18112233 IDENT : FR99ZZZ112233'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE IRIADE REF : PREL-IRIAD 4 411223344 41 716 IRIADE-1016-411223344 1 1 1-4F24'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::VariousInsurance, 'PRELEVEMENT DE LBP ASSURANCES IA REF : 160020112233 XXX00160020112233 NP23112233 IDENT : FR99ZZZ112233'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB CFTA RHONE     04.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF VOYAGEURS 04.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesFastFood, 'ACHAT CB BURGER KING    04.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB Osterr.Postbus 04.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB Hofer Dankt    04.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB RELAY OCCITAN  04.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB HotelSchaniDon 04.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB WIENER LINIEN  04.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB WIENER LINIEN  04.12.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181340411223344'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038673112233 1038673112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalAccounting, 'ACHAT CB INDY COMPTABIL 03.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB Revolut  2951  03.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'CREDIT CARTE BANCAIRE SCW  C-6925     03.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181338481122344'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT PERMANENT POUR MR ALLIAUME HUGO COMPTE FR99********************* REFERENCE : 0226338411223344'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038625112233 1038625112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038586112233 1038586112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::HousingOutdoorAndGarden, 'ACHAT CB BOTANIC        02.12.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::SubscriptionInternet, 'PRELEVEMENT DE Orange SA REF : 4C999X999 C816L1234X123X Votre abonnement fibre (facture: XXX1174I4)'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 29.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CASA SOLARI    29.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 29.11.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalOnlineService, 'ACHAT CB Google GSUITEa 01.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB FRANPRIX       30.11.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SCW  C-6925    02.12.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038511223344 1038511223344/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 27.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038411223344 1038411223344/PAYPAL'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE Hugo Alliaume Envoye depuis Revolut'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::TaxesAndDuties, 'PRELEVEMENT DE DIRECTION GENERAL ES FINANCES PUBL REF : 299990000XYZ1122334455667 055 03'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038311223344 1038311223344/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038311223344 1038311223344/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038311223344 1038311223344/PAYPAL'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB MOMENTO FAMILY 23.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::Unknown, 'ACHAT CB EMMAUS LYON    23.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB ZETTLE  OTEA V 23.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesRestaurant, 'ACHAT CB CHIKIN BANG    23.11.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB  CUMUL         23.11.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB BHN            23.11.24 EUR          1,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181328411223344'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesRestaurant, 'ACHAT CB CHIKIN BANG    21.11.24 EUR         22,00 CARTE NO  999 APPLE PAY'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::SubscriptionMobileTelephony, 'PRELEVEMENT DE Orange SA REF : 163237XXXXXXXXXXXXXXXX236 0 Votre abonnement mobile: 07XXXXX'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::TaxesAndDuties, 'PRELEVEMENT DE DIRECTION GENERAL ES FINANCES PUBL REF : 1E000011223344M1122334455 691122334455667788 222'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalOnlineService, 'ACHAT CB CLOUDFLARE     17.11.24 USD         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingMiscellaneousExpenses, 'PRELEVEMENT DE SDC LES NOUVELLES CHES REF : SIG/75678010/2024-11-15 PRELEVEMENT DU 15/11/2024'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038171112233 1038171112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingElectricity, 'PRELEVEMENT DE EDF clients parti iers REF : Z125052836574 11406 1 S 114'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038079112233 1038079112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038148112233 1038148112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1038145112233 1038145112233/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::PurchasesAndShoppingHighTech, 'ACHAT CB APPLE.COM/FR   08.11.24 EUR       4444,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB GOCHI          10.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF VOYAGEURS 10.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 09.11.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB  CUMUL         07.11.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB SERVICE NAVIGO 07.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181313411223344'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB LES TONTONS BR 06.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB LES TONTONS BR 06.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'CREDIT CARTE BANCAIRE SNCF-VOYAGEURS  06.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'CREDIT CARTE BANCAIRE SNCF-VOYAGEURS  06.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::LeisureSport, 'PRELEVEMENT DE SAS Fitness Ville nche REF : apt-11-1122334-aaAABBcc L Appart Fitness Villefranche -'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::AestheticAndCareHair, 'ACHAT CB L EPICURIE    05.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE ECHEANCE PRET REF : 241030178071 2099XXXX99X99999    E0040073O1 IDENT : FR99XXX112233'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::VariousInsurance, 'PRELEVEMENT DE LBP ASSURANCES IA REF : 160017878999 XXX00160017878999 NM18112233 IDENT : FR99ZZZ112233'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1031122334455 1031122334455/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE IRIADE REF : PREL-IRIAD 4 411223344 41 178 IRIADE-1016-411223344 1 1 1-4F24'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::VariousInsurance, 'PRELEVEMENT DE LBP ASSURANCES IA REF : 160011223344 XXX00160011223344 NP23112233 IDENT : FR99ZZZ112233'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF-VOYAGEURS 04.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT PERMANENT POUR MR ALLIAUME HUGO COMPTE FR99********************* REFERENCE : 0226301122334455'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT POUR M ALLIAUME HUGO COMPTE FR99********************* DEFAULT'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1031122334455 1031122334455/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 01.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF VOYAGEURS 02.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::HousingOutdoorAndGarden, 'ACHAT CB BOTANIC        01.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalOnlineService, 'ACHAT CB Google GSUITE  01.11.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF-VOYAGEURS 02.11.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 01.11.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE Hugo Alliaume Envoye depuis Revolut'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 30.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesRestaurant, 'ACHAT CB EURO D ASIE    29.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'CREDIT CARTE BANCAIRE AMAZON PRIME FR 29.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181304411223344'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::SubscriptionInternet, 'PRELEVEMENT DE Orange SA REF : 4C999X999 C****1122X123X Votre abonnement fibre (facture: XXX1174H6)'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1031122334455 1031122334455/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal (Europe) S r.l. et Cie, S.C REF : 1031122334455 PAYPAL VIRE 1031122334455 PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1031122334455 1031122334455/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1031122334455 1031122334455/PAYPAL'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingOther, 'ACHAT CB AMAZON PRIME F 25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 27.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB LE COSY        26.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 27.10.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB GNTI           25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SC-REST PROVID 25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB RATP           25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SUMUP   VOLPI  27.10.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SUPER 15V      25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB RATP           26.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB MONOPRIX 2326  25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SUPER 15V      25.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0111223344556677'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::TaxesAndDuties, 'PRELEVEMENT DE DIRECTION GENERAL ES FINANCES PUBL REF : 299990000XYZ1122334455667 055 02'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB PHIE CALADOISE 23.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1031122334455 1031122334455/PAYPAL'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingOther, 'ACHAT CB AMAZON PAYMENT 21.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 22.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181296480022445'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::SubscriptionMobileTelephony, 'PRELEVEMENT DE Orange SA REF : 1632375290656173373252176 0 Votre abonnement mobile: 07XXXXX'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesOther, 'ACHAT CB PATISS NICOLAS 18.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesFastFood, 'ACHAT CB BURGERKING FR  19.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB La table Vermo 17.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalOnlineService, 'ACHAT CB CLOUDFLARE     17.10.24 USD         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CASA SOLARI    16.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 16.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::TaxesAndDuties, 'PRELEVEMENT DE DIRECTION GENERAL ES FINANCES PUBL REF : 1E000011223344M1122334455 691122334455667788 222'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0181112233445566'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT POUR HUGO ALLIAUME COMPTE FR76********************* SKI 2/2'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT POUR M ALLIAUME HUGO COMPTE FR99********************* RETOUR AVANCE SKI'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingMiscellaneousExpenses, 'PRELEVEMENT DE SDC LES NOUVELLES CHES REF : SIG/71122334/2024-10-15 PRELEVEMENT DU 15/10/2024'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 14.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 14.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT POUR HUGO ALLIAUME COMPTE FR76********************* SKI 1/2 (REPAREZ LE PAIEMENT 3DS'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingElectricity, 'PRELEVEMENT DE EDF clients parti iers REF : Z121122334455 11406 1 S 114'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF VOYAGEURS 11.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingSport, 'ACHAT CB DECATHLON      12.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 12.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 12.10.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB EARL OF SANDWI 10.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::LeisureOther, 'ACHAT CB EURO DISNEY AS 10.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB RATP           10.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesRestaurant, 'ACHAT CB CHIKIN BANG    09.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB TRAN TRAN ZAI  09.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB YITHE          09.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportPublicTransport, 'ACHAT CB RATP           09.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingSport, 'ACHAT CB DECATHLON      07.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE M ABCDEFGH ABCDEFGH Virement de Abcdefgh ABCDEFGH Ski REFERENCE : 0190112233445566'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE ECHEANCE PRET REF : 241122334455 2099XXXX99X99999    E0040072O1 IDENT : FR99XXX112233'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::LeisureSport, 'PRELEVEMENT DE SAS Fitness Ville nche REF : apt-10-1122334-aaAABBcc L Appart Fitness Villefranche -'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE IRIADE REF : PREL-IRIAD 4 411223344 41 148 IRIADE-1016-411223344 1 1 1-4F24'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB TRAVEL FACTO.C 04.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CARREFOUR      04.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 06.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 04.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesOther, 'ACHAT CB PATISS NICOLAS 06.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'VIREMENT DE PayPal Europe S.a.r. et Cie S.C.A XYZ1112233445566 XYZ1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE M. ABCDEFGH ABCDEFGH SKI CHARPENTAX'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE M     ABCDEFGH ABCDEFGH Virement de M ABCDEFGH ABCDEFGH Virement de M ABCDEFGH ABCDEFGH'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MLE ABCDEFGH ABCDEFGH VG123456XXXXXX11 REMBOURSEMENT CHALET SKI ABCDEFGH REFERENCE : 0111223344556677'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE ABCDEFGH ABCDEFGH SKI ABCDEFGH REFERENCE : 0111223344556677'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO PREMIER PAIEMENT SKI REFERENCE : 0111223344556677'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE LBP IARD REF : 61122334455 XXX00061122334455 NM18112233 IDENT : FR99ZZZ112233'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal (Europe) S r.l. et Cie, S.C REF : 1037314861997 PAYPAL VIRE 1037314861997 PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'PRELEVEMENT DE LBP IARD REF : 61122334455 XXX00061122334455 NP23112233 IDENT : FR99ZZZ112233'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::Unknown, 'AVANTAGE SEUIL DE NON-PERCEPTION D AGIOS'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::Unknown, 'MINIMUM FORFAITAIRE TRIMESTRIEL D UTILISATION DU DECOUVERT'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT PERMANENT POUR MR ALLIAUME HUGO COMPTE FR99********************* REFERENCE : 0211223344556677'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB HELLOASSO  BIL 02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB INTERGLEIZE DI 02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 02.10.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankLoanRepayment, 'COTISATION TRIMESTRIELLE DE VOTRE FORMULE DE COMPTE APRES REDUCTION JEUNES 26-29 ANS DE 22,00'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'CREDIT CARTE BANCAIRE SNCF INTERNET   02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'CREDIT CARTE BANCAIRE SNCF INTERNET   02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'CREDIT CARTE BANCAIRE SNCF INTERNET   02.10.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::BankCharges, 'AVANTAGE TARIFAIRE PATRIMONIAL SUR COTISATION FORMULE DE COMPTE'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1112233445566 1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalOnlineService, 'ACHAT CB Google GSUITE  01.10.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1112233445566 1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::SubscriptionInternet, 'PRELEVEMENT DE Orange SA REF : 4C999X999 C999X9999X999X Votre abonnement fibre (facture: XXX9999X9)'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingSport, 'ACHAT CB DECATHLON      28.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 28.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 29.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CASA SOLARI    27.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 29.09.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB MAGASIN U      27.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 27.09.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  27.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB FRANPRIX       29.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO DEFAULT REFERENCE : 0111223344556677'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::TaxesAndDuties, 'PRELEVEMENT DE DIRECTION GENERAL ES FINANCES PUBL REF : 299990000XYZ1122334455667 055 01'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::AestheticAndCareHair, 'ACHAT CB L EPICURIE    25.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 25.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 24.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesOther, 'ACHAT CB HENRI DESMOULI 24.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::HousingOutdoorAndGarden, 'ACHAT CB BOTANIC        24.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1112233445566 1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1112233445566 1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  21.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 21.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 21.09.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  20.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::SubscriptionMobileTelephony, 'PRELEVEMENT DE Orange SA REF : 1112233445566778899112233 0 Votre abonnement mobile: 07XXXXX'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB SUMUP   SYMFON 19.09.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB ILEVIA DAT MET 19.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  19.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  19.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  18.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CARREFOUR SCT  18.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::ProfessionalOnlineService, 'ACHAT CB CLOUDFLARE     17.09.24 USD         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::TaxesAndDuties, 'PRELEVEMENT DE DIRECTION GENERAL ES FINANCES PUBL REF : 1E000011223344M1122334455 691122334455667788 222'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::Various, 'ACHAT CB BRICO DEPOT    16.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 16.09.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 16.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingMiscellaneousExpenses, 'PRELEVEMENT DE SDC LES NOUVELLES CHES REF : SIG/11223344/2024-09-15 PRELEVEMENT DU 15/09/2024'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 13.09.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB CHAHINE        15.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 13.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  13.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1112233445566 1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CARREFOUR      12.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::HousingElectricity, 'PRELEVEMENT DE EDF clients parti iers REF : Z112233445566 11406 1 S 114'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::LeisureHotel, 'ACHAT CB BOOKING.COM    11.09.24 EUR        333,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB LUFTHANSA   22 11.09.24 EUR        333,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::FoodAndGroceriesRestaurant, 'ACHAT CB SUSHI 6EME     11.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  11.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF VOYAGEURS 11.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingOther, 'ACHAT CB AMAZON PAYMENT 08.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT DE MR ALLIAUME HUGO VIENNE REFERENCE : 0111223344556677'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB GRAND FRAIS VI 10.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'VIREMENT DE PayPal Europe S.a.r. et Cie S.C.A XXX1122334455667 XXX1122334455667/PAYPAL'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 09.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 09.09.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::PurchasesAndShoppingOther, 'ACHAT CB AMAZON PAYMENT 08.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB CRF VILLEFRANC 06.09.24 EUR         22,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 06.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::FoodAndGroceriesSupermarket, 'ACHAT CB BOUCHERIES AND 06.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB APRR VILLEFRAN 08.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Essential, BankTransactionCategory::Withdrawal, 'CARTE X2458    06/09/24 A 12H10 RETRAIT DAB VILLEFRANCHE S'])]
    #[TestWith([BankTransactionType::Extra, BankTransactionCategory::VariousPayPal, 'PRELEVEMENT DE PayPal Europe S.a l. et Cie S.C.A REF : 1112233445566 1112233445566/PAYPAL'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB CFTA RHONE     05.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Pleasure, BankTransactionCategory::TransportTrainTicket, 'ACHAT CB SNCF INTERNET  05.09.24 CARTE NUMERO                123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'ACHAT CB VENPAY IVS     05.09.24 EUR          1,00 CARTE NO  123'])]
    #[TestWith([BankTransactionType::Unknown, BankTransactionCategory::Unknown, 'VIREMENT INSTANTANE DE Hugo Alliaume Envoye depuis Revolut'])]
    public function testGuess(BankTransactionType $expectedType, BankTransactionCategory $expectedCategory, string $label): void
    {
        [$type, $category] = TypeAndCategoryGuesser::guess($label);

        self::assertSame($expectedType, $type, sprintf('Transaction "%s" should be of type "%s"', $label, $expectedType->value));
        self::assertSame($expectedCategory, $category, sprintf('Transaction "%s" should be of category "%s"', $label, $expectedCategory->value));
    }
}
